### ISSUE TITLE
phone_number_argument_error

### ISSUE THREAD

**Issue by sbezugliy** [Fnux/telegram-mt-elixir#15]
When trying to serialize auth.sendCode message:

`TL.build("auth.sendCode", %{phone_number: "569123458754", sms_type: 0, api_id: "12345", api_hash: "fJHffhjHFhgfdJH", lang_code: "en"})`

I have error:
> ** (ArgumentError) argument error
>     (telegram_tl) lib/tl/build.ex:72: TL.Build.serialize/2
>     (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
>     (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
>     (telegram_tl) lib/tl/build.ex:25: TL.Build.encode/2

**Comment by Fnux** [comment]
This issue is related to [telegram-tl-elixir](https://github.com/Fnux/telegram-tl-elixir) :-) The `api_id` field should be an integer : 
```
iex> TL.build("auth.sendCode", %{phone_number: "569123458754", sms_type: 0, api_id: 12345, api_hash: "fJHffhjHFhgfdJH", lang_code: "en"})  
<<236, 240, 174, 134, 0, 0, 0, 0, 12, 53, 54, 57, 49, 50, 51, 52, 53, 56, 55,
  53, 52, 0, 0, 0, 57, 48, 0, 0, 15, 102, 74, 72, 102, 102, 104, 106, 72, 70,
  104, 103, 102, 100, 74, 72>> 
```

PS: This project is **not stable** yet ! I don't have a lot of time to work on it for now.

**Comment by sbezugliy** [comment]
Ok. Thanks.
I see some errors when trying to authenticate. Looks like related to delays. And warnings in encryption/decriyption. Will try to debug.

**Comment by Fnux** [comment]
The main issue is the generation of the authorization key : it fails sometimes and I still don't know why.

Otherwise you should be able to send/receive contacts and text messages (files are not yet implemented). Feel free to ask me anything [0] since it's probably a bit messy !

[0] issue, mail, irc, ...
